# Strategy: QqqMonthlyDCA
# Spec:     data/strategies/qqq-monthly-dca.md
# Generated by: strategy-builder
#
# Runtime dependencies (Strategy, RULES, pd) are injected by run_backtest.py.
# Do not add import statements to this file.

METADATA = {
    "name": "QqqMonthlyDCA",
    "label": "QqqMonthlyDCA | Calendar(daily)",
    "rebalance_rule": "daily",
    "suitable_for": {
        "min_horizon_years": 10,
        "risk_tolerance": ["moderate", "aggressive"],
        "asset_types": ["ETF"],
        "max_drawdown_tolerance": -0.45,
        "notes": "QQQ-only with intra-month DCA. Spreads monthly re-entry over every trading day to reduce timing risk vs lump-sum.",
    },
}


class QqqMonthlyDCA(Strategy):
    min_rebalance_frequency = "daily"
    suitable_for = METADATA["suitable_for"]

    def __init__(self, tickers, **kwargs):
        super().__init__(tickers, **kwargs)
        self.name = "QqqMonthlyDCA"
        self._month_days = {}

    def _get_month_days(self, prices, year, month):
        key = (year, month)
        if key not in self._month_days:
            mask = (prices.index.year == year) & (prices.index.month == month)
            self._month_days[key] = list(prices.index[mask])
        return self._month_days[key]

    def get_weights(self, prices, as_of):
        if "QQQ" not in prices.columns:
            return {}
        month_days = self._get_month_days(prices, as_of.year, as_of.month)
        if not month_days or as_of not in month_days:
            return {}
        day_idx = month_days.index(as_of)
        n = len(month_days)
        qqq_w = round((day_idx + 1) / n, 6)
        result = {"QQQ": qqq_w}
        if qqq_w < 1.0 and "SHY" in prices.columns:
            result["SHY"] = round(1.0 - qqq_w, 6)
        return result


STRATEGY_CLASS = QqqMonthlyDCA
RULE = RULES["daily"]
